// Generated by CoffeeScript 1.3.3
var formatBold, formatBorder, formatCheckbox, formatFrame, formatItalic, formatLineThrough, formatListTable, formatOL, formatPercent, formatPlain, formatReadOnly, formatSpan, formatSticker, formatTD, formatTH, formatUL, formatUnderline, formatYesNo, setMenuFormat;

setMenuFormat = function() {
  $(".format_bold").click(formatBold);
  $(".format_italic").click(formatItalic);
  $(".format_underline").click(formatUnderline);
  $(".format_linethrough").click(formatLineThrough);
  $(".format_border").click(formatBorder);
  $(".format_span").click(formatSpan);
  $(".format_th").click(formatTH);
  $(".format_td").click(formatTD);
  $(".format_sticker").click(formatSticker);
  $(".format_plain").click(formatPlain);
  $(".format_ol").click(formatOL);
  $(".format_ul").click(formatUL);
  $(".format_checkbox").click(formatCheckbox);
  $(".format_yesno").click(formatYesNo);
  $(".format_percent").click(formatPercent);
  $(".format_frame").click(formatFrame);
  $(".format_readonly").click(formatReadOnly);
  return $(".format_listtable").click(formatListTable);
};

formatBold = function() {
  if (sidea.bold != null) {
    delete sidea.bold;
  } else {
    sidea.bold = true;
  }
  return redraw();
};

formatItalic = function() {
  if (sidea.italic != null) {
    delete sidea.italic;
  } else {
    sidea.italic = true;
  }
  return redraw();
};

formatUnderline = function() {
  if (sidea.underline != null) {
    delete sidea.underline;
  } else {
    sidea.underline = true;
  }
  return redraw();
};

formatBorder = function() {
  if (sidea.border != null) {
    delete sidea.border;
  } else {
    sidea.border = true;
  }
  return redraw();
};

formatLineThrough = function() {
  if (sidea.linethrough != null) {
    delete sidea.linethrough;
  } else {
    sidea.linethrough = true;
  }
  return redraw();
};

formatSpan = function() {
  if (sidea !== fidea) {
    if ((sidea.list != null) && sidea.list === SPAN) {
      delete sidea.list;
    } else {
      sidea.list = SPAN;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatTD = function() {
  if (sidea !== fidea) {
    if ((sidea.list != null) && sidea.list === TD) {
      delete sidea.list;
    } else {
      sidea.list = TD;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatSticker = function() {
  if (sidea !== fidea) {
    if ((sidea.list != null) && sidea.list === STICKER) {
      delete sidea.list;
    } else {
      sidea.list = STICKER;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatFrame = function() {
  finishEdit();
  if (sidea.frame != null) {
    delete sidea.frame;
    return sidea.upperFrame().fhtml(sidea);
  } else {
    sidea.frame = true;
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatReadOnly = function() {
  if (sidea.readonly != null) {
    delete sidea.readonly;
  } else {
    sidea.readonly = true;
  }
  return redraw();
};

formatPlain = function() {
  if (sidea !== fidea) {
    if (sidea.plain != null) {
      delete sidea.plain;
    } else {
      sidea.plain = true;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatOL = function() {
  if (sidea !== fidea) {
    if ((sidea.list != null) && sidea.list === OL) {
      delete sidea.list;
    } else {
      sidea.list = OL;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatUL = function() {
  if (sidea !== fidea) {
    if ((sidea.list != null) && sidea.list === UL) {
      delete sidea.list;
    } else {
      sidea.list = UL;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatCheckbox = function() {
  if (sidea !== fidea) {
    if ((sidea.format != null) && sidea.format === CHECKBOX) {
      delete sidea.format;
    } else {
      sidea.format = CHECKBOX;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatYesNo = function() {
  if (sidea !== fidea) {
    if ((sidea.format != null) && sidea.format === YESNO) {
      delete sidea.format;
    } else {
      sidea.format = YESNO;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatPercent = function() {
  if (sidea !== fidea) {
    if ((sidea.format != null) && sidea.format === PERCENT) {
      delete sidea.format;
    } else {
      sidea.format = PERCENT;
    }
    return sidea.upperFrame().fhtml(sidea);
  }
};

formatListTable = function() {
  if (sidea.intype != null) {
    if (sidea.intype === LIST) {
      sidea.intype = LINE;
    } else if (sidea.intype === LINE) {
      sidea.intype = TABLE;
    } else if (sidea.intype === TABLE) {
      sidea.intype = LIST;
    }
  } else {
    sidea.intype = LINE;
  }
  return redraw();
};

formatTH = function() {
  if (sidea.th != null) {
    delete sidea.th;
  } else {
    sidea.th = true;
  }
  return redraw();
};
