// Generated by CoffeeScript 1.3.3

keyp[GEM] = {};

childkind[GEM] = function() {
  return null;
};

notxt[GEM] = true;

Idea.prototype.kindGem = function() {
  return this.kind = GEM;
};

drtxt[GEM] = function(level) {
  var s;
  s = "";
  s += "<div class='gem'>&nbsp;</div>";
  console.log("gem");
  return s;
};

draw[GEM] = function(level) {
  return this.simpleIdeaTxt(level, DRAWALL);
};
