// Generated by CoffeeScript 1.3.3
var AARROW, ACTIVE, AFTER, BAG, BARROW, BCG, BCGCELL, BCGCOLUMN, BCGCOLUMNS, BCGCORNER, BCGENTITY, BCGROW, BCGROWCELL, BCGROWS, BEFORE, BLACK, BLOCK, BLOCKS, BLUE, BLUEOCEAN, BONE, BOTTOM, BUTTON, CANVASJS, CARROW, CELL, CENTER, CHAR, CHARS, CHECKBOX, CIRCLE, COLUMN, COLUMNS, COMMENT, CORNER, COURT, CSSOVAL, CSSRECT, CSSRRECT, DAISY, DEFAULT, DESCRIPTION, DH, DOC, DRAWALL, DRAWCHILDREN, DRAWHEADER, DW, EDGE, EXAMPLE, FACT, FIELD, FIELDS, GANTT, GANTTPERIOD, GANTTPHASE, GANTTPHASES, GANTTRESULT, GANTTRESULTS, GANTTSTAGE, GEM, GREEN, GROUP, GUIDE, HLANE, ICON, IDEA, IMAGE, INLINE, INSIDE, ISHIKAWA, JUSTIFY, KNOT, LAYER, LEFT, LIGHTBLUE, LINE, LINK, LIST, MAINMENU, MAP, MAPTABLE, MATRIX, MENU, MENUITEM, MIDDLE, MINDCENTER, MINDLEAF, MINDLEFT, MINDMAP, MINDRIGHT, NATIVE, NODE, NUMBER, OCEAN, OL, OLIST, OUTSIDE, OVAL, PA, PANEL, PAPERJS, PASSIVE, PERCENT, PETAL, PIE, PIECHART, PIEPART, PRESENTATION, PYRAMID, RAPHAELJS, RECORD, RECT, RED, RIGHT, ROW, ROWCELL, ROWS, RRECT, RULE, SCRH, SCRW, SLIDE, SPAN, STICKER, TAB, TABLE, TABLEAU, TABS, TAG, TBL, TD, TEXT, TH, TICK, TODO, TOP, TREE, TREEDOWN, TREELEFT, TREERIGHT, TREEROOT, TREEUP, TXT, UL, ULIST, VALUE, VLANE, WHITE, YELLOW, YESNO, bkgStyle, btnClass, kkind, kkindname, method, panelClass, sample, schemes, tblClass;

method = {};

sample = {};

SCRH = 400;

SCRW = 900;

DW = 20;

DH = 20;

DEFAULT = -100;

IDEA = -200;

LINK = -210;

PYRAMID = -300;

LAYER = -310;

MATRIX = -400;

CORNER = -410;

ROWS = -420;

ROW = -430;

COLUMNS = -440;

COLUMN = -450;

CELL = -460;

ROWCELL = -470;

MAINMENU = -500;

MENU = -510;

MENUITEM = -520;

STICKER = -600;

TODO = -610;

DESCRIPTION = -620;

GUIDE = -630;

EXAMPLE = -640;

COMMENT = -650;

TABLE = -700;

FIELDS = -710;

FIELD = -720;

RECORD = -730;

VALUE = -740;

TABLEAU = -750;

LINE = -760;

BLOCKS = -800;

BLOCK = -810;

PIECHART = -900;

MINDMAP = -1000;

MINDLEAF = -1010;

MINDLEFT = -1020;

MINDRIGHT = -1030;

MINDCENTER = -1040;

TREE = -1100;

KNOT = -1110;

TREELEFT = -1120;

TREERIGHT = -1130;

TREEUP = -1140;

TREEDOWN = -1150;

TREEROOT = -1160;

DOC = -1200;

TEXT = -1210;

PA = -1300;

UL = -1310;

OL = -1320;

SPAN = -1330;

TD = -1340;

TH = -1350;

INLINE = -1360;

LIST = -1370;

OLIST = -1380;

ULIST = -1390;

PERCENT = -1400;

NUMBER = -1410;

CHECKBOX = -1420;

YESNO = -1430;

TABS = -1500;

TAB = -1510;

FACT = -1600;

RULE = -1610;

BUTTON = -1700;

PANEL = -1710;

PRESENTATION = -1800;

SLIDE = -1810;

MAP = -1900;

NODE = -1910;

EDGE = -1920;

HLANE = -1930;

VLANE = -1940;

COURT = -1950;

GROUP = -1960;

MAPTABLE = -1970;

ISHIKAWA = -2000;

BONE = -2010;

BCG = -2100;

BCGCORNER = -2110;

BCGCOLUMNS = -2120;

BCGCOLUMN = -2130;

BCGROWS = -2140;

BCGROW = -2150;

BCGROWCELL = -2150;

BCGCELL = -2160;

BCGENTITY = -2170;

GANTT = -2200;

GANTTPERIOD = -2210;

GANTTSTAGE = -2220;

GANTTPHASES = -2230;

GANTTPHASE = -2240;

GANTTRESULTS = -2250;

GANTTRESULT = -2260;

BLUEOCEAN = -2300;

OCEAN = -2310;

CHARS = -2320;

CHAR = -2330;

RRECT = -2400;

RECT = -2410;

OVAL = -2420;

CIRCLE = -2422;

AARROW = -2430;

BARROW = -2432;

CARROW = -2434;

ACTIVE = -2500;

PASSIVE = -2510;

NATIVE = -2520;

LEFT = -2600;

CENTER = -2610;

RIGHT = -2620;

JUSTIFY = -2630;

TOP = -2640;

MIDDLE = -2650;

BOTTOM = -2660;

INSIDE = -2670;

OUTSIDE = -2675;

BEFORE = -2680;

AFTER = -2690;

PIE = -2700;

PIEPART = -2710;

WHITE = -2800;

BLUE = -2810;

LIGHTBLUE = -2820;

GREEN = -2830;

YELLOW = -2840;

RED = -2850;

BLACK = -2860;

TBL = -2900;

BAG = -2910;

TXT = -2920;

RAPHAELJS = -3000;

PAPERJS = -3010;

CANVASJS = -3020;

TICK = -3100;

TAG = -3110;

ICON = -3120;

IMAGE = -3130;

GEM = -3140;

DRAWALL = -3200;

DRAWHEADER = -3210;

DRAWCHILDREN = -3220;

CSSRECT = -3310;

CSSRRECT = -3320;

CSSOVAL = -3330;

DAISY = -3400;

PETAL = -3410;

bkgStyle = [];

bkgStyle.push("#FFD url('/img/grid-18px-masked.png') repeat-x");

bkgStyle.push("#FFF url('/img/back-sky.jpg') no-repeat");

tblClass = [];

tblClass.push("normaltable");

tblClass.push("guidetable");

btnClass = {};

btnClass[WHITE] = 'panel-white';

btnClass[BLUE] = 'panel-blue';

btnClass[LIGHTBLUE] = 'btn btn-info';

btnClass[GREEN] = 'btn btn-success';

btnClass[YELLOW] = 'btn btn-warning';

btnClass[RED] = 'btn btn-darger';

btnClass[BLACK] = 'btn btn-inverse';

panelClass = {};

panelClass[WHITE] = 'panel-white';

panelClass[BLUE] = 'panel-black';

schemes = {};

schemes[WHITE] = ["white", "#ffffff", "#e6e6e6", "#bfbfbf", "Black", "Yellow"];

schemes[BLUE] = ["blue", "#0088cc", "#0055cc", "#003580", "White", "Magenta"];

schemes[LIGHTBLUE] = ["lightblue", "#5bc0de", "#2f96b4", "#1f6377", "White", "Cyan"];

schemes[GREEN] = ["green", "#62c462", "#51a351", "#387038", "White", "#c0ffc0"];

schemes[YELLOW] = ["yellow", "#fbb450", "#f89406", "#ad6704", "White", "#c0ffff"];

schemes[RED] = ["red", "#ee5f5b", "#bd362f", "#802420", "White", "#c0c0c0"];

schemes[BLACK] = ["black", "#555555", "#222222", "#000000", "White", "#ffffff"];

kkind = [IDEA, ULIST, OLIST, TICK, GEM, ICON, TAG, IMAGE, STICKER, MINDMAP, TREE];

kkindname = ["Идея", "Ненумерованный список", "Нумерованный список", "Галочка", "Камешек", "Иконка", "Тэг", "Картинка", "Стикер", "Интеллектуальная<br>карта", "Дерево"];
