// Generated by CoffeeScript 1.3.3
var icons;

keyp[ICON] = {};

childkind[ICON] = function() {
  return null;
};

notxt[ICON] = true;

Idea.prototype.kindIcon = function() {
  return this.kind = ICON;
};

icons = [];

icons.push("pencil");

icons.push("pencil-2");

icons.push("home");

icons.push("home-2");

icons.push("home-3");

icons.push("newspaper");

drtxt[ICON] = function(level) {
  var s;
  s = "";
  if (this.val != null) {
    s += "<span class='nicon-" + icons[this.val] + "'></span>";
  } else {
    s += "<span class='nicon-home'></span>";
  }
  return s;
};

draw[ICON] = function(level) {
  return this.simpleIdeaTxt(level);
};

clas[ICON] = "iicon";

keyp[ICON][KEY_ENTER] = function() {
  if (this.val == null) {
    this.val = -1;
  }
  this.val = (this.val + 1) % icons.length;
  return fidea.fhtml(sidea);
};

keyp[ICON][KEY_F2] = keyp[ICON][KEY_ENTER];
