// Generated by CoffeeScript 1.3.3
var images;

keyp[IMAGE] = {};

childkind[IMAGE] = function() {
  return null;
};

notxt[IMAGE] = true;

Idea.prototype.kindImage = function() {
  return this.kind = IMAGE;
};

images = [];

images.push({
  url: "korablik.jpg",
  w: 600,
  h: 598
});

drtxt[IMAGE] = function(level) {
  var s;
  s = "<img ";
  if (this.val != null) {
    s += " src='methods/" + images[this.val].url + "' ";
    s += " width='" + images[this.val].w + "px' ";
    s += " height='" + images[this.val].h + "px' ";
  } else {
    if (this.url != null) {
      s += " src='methods/" + this.url + "' ";
    }
    if (this.w != null) {
      s += " width='" + this.w + "px'";
    }
    if (this.h != null) {
      s += " height='" + this.h + "px'";
    }
    s += " style='";
    if (this.w != null) {
      s += "width:" + this.w + "px;";
    }
    if (this.h != null) {
      s += "height:" + this.h + "px;";
    }
    s += "'";
  }
  s += ">";
  return s;
};

clas[IMAGE] = "image";
