// Generated by CoffeeScript 1.3.3

keyp[OLIST] = {};

childkind[OLIST] = function() {
  return null;
};

notxt[OLIST] = true;

keyp[ULIST] = {};

childkind[ULIST] = function() {
  return null;
};

notxt[ULIST] = true;

drtxt[OLIST] = function(level) {
  var s, _ref, _ref1, _ref2, _ref3;
  s = "";
  this.val = 1;
  if (((_ref = this.pa[this.sd - 1]) != null ? (_ref1 = _ref[this.ix]) != null ? _ref1.kind : void 0 : void 0) === OLIST && (((_ref2 = this.pa[this.sd - 1]) != null ? (_ref3 = _ref2[this.ix]) != null ? _ref3.val : void 0 : void 0) != null)) {
    this.val = this.pa[this.sd - 1][this.ix].val + 1;
  }
  s += this.val + ".";
  return s;
};

clas[OLIST] = "olist";

drtxt[ULIST] = function(level) {
  var s;
  s = "";
  s += "&nbsp;\u2022&nbsp;";
  return s;
};

clas[ULIST] = "list";
