// Generated by CoffeeScript 1.3.3

canvastype[PIE] = function() {
  return ACTIVE;
};

keyp[PIE] = {};

keyp[PIEPART] = {};

childkind[PIE] = function() {
  return PIEPART;
};

childkind[PIEPART] = function() {
  return IDEA;
};

afterinsert[PIE] = function() {
  return this.pa.kindPie();
};

Idea.prototype.kindPie = function() {
  var i, ia, _i, _len, _ref, _results;
  this.kind = PIE;
  _ref = this.data;
  _results = [];
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    ia = _ref[i];
    ia.pa = this;
    ia.ix = i;
    ia.kind = PIEPART;
    if (ia.val == null) {
      _results.push(ia.val = 0.1);
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

draw[PIE] = function(level) {
  var ia, s, _i, _len, _ref;
  s = this.startIdeaTxt(level);
  _ref = this.data;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    ia = _ref[_i];
    s += ia.draw(level + 1);
  }
  return s += this.endIdeaTxt(level);
};

paint[PIE] = function(level, ppr) {
  var i, ia, start, _i, _len, _ref, _results;
  ppr.setSize(400, 400);
  v[this.id] = {};
  v[this.id].x = 200;
  v[this.id].y = 200;
  start = 0;
  _ref = this.data;
  _results = [];
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    ia = _ref[i];
    ia.paintPiePart(i, start, ia.val, ppr);
    _results.push(start += ia.val);
  }
  return _results;
};

Idea.prototype.paintPiePart = function(n, start, value, ppr) {
  var alpha, as, beta, gamma, x1, x2, y1, y2;
  alpha = start * 2 * Math.PI;
  beta = (start + value) * 2 * Math.PI;
  gamma = (start + value / 2) * 2 * Math.PI;
  $("#bag" + this.id).addClass("mindbag");
  v[this.id] = {};
  v[this.id].w = $("#bag" + this.id).outerWidth(true);
  v[this.id].h = $("#bag" + this.id).outerHeight(true);
  console.log(v[this.id].w, v[this.id].h);
  x1 = v[this.pa.id].x + 175 * Math.sin(alpha);
  y1 = v[this.pa.id].y - 175 * Math.cos(alpha);
  x2 = v[this.pa.id].x + 175 * Math.sin(beta);
  y2 = v[this.pa.id].y - 175 * Math.cos(beta);
  as = "M " + v[this.pa.id].x + " " + v[this.pa.id].y + "		L " + x1 + " " + y1 + "		A 175 175 0 0 1 " + x2 + " " + y2 + " z";
  g[this.id] = ppr.path(as);
  g[this.id].attr({
    "stroke": "#888",
    "stroke-opacity": 0.5,
    "stroke-width": 1,
    "fill": "90-#FF9-#FFE",
    "fill-opacity": 1
  });
  $("#bag" + this.id).css("position", "absolute");
  $("#bag" + this.id).css("left", v[this.pa.id].x + 100 * Math.sin(gamma) - v[this.id].w / 2);
  return $("#bag" + this.id).css("top", v[this.pa.id].y - 100 * Math.cos(gamma) - v[this.id].h / 2);
};
