// Generated by CoffeeScript 1.3.3

svg[PIECHART] = function() {
  var pie1, pie2, pp, re, ri, _i, _len, _ref;
  ppr[this.id] = Raphael("pap" + this.id, 500, 320);
  pp = $('#pap' + this.id).position();
  $('#bag' + this.id).height($('#txt' + this.id).outerHeight(true) + $('#pap' + this.id).outerHeight(true));
  pie1 = [];
  pie2 = [];
  if (this.source != null) {
    _ref = this.source.data;
    for (ri = _i = 0, _len = _ref.length; _i < _len; ri = ++_i) {
      re = _ref[ri];
      pie1[ri] = re[0].txt;
      pie2[ri] = Number(re[1].txt);
    }
    return g[this.id] = ppr[this.id].piechart(300, 170, 130, pie2, {
      legend: pie1,
      legendpos: "west",
      href: ["http://minday.ru", "http://minday.ru"]
    });
  }
};

draw[PIECHART] = function(level) {
  var s;
  s = this.htmlIdeaTxt(level);
  if ((level === 0) || (level > 0 && !(this.frame != null))) {
    svga.push(this);
    s += "<div id='pap" + this.id + "'></div>";
  }
  s += "</div>";
  return s;
};

/*
html[LAYER] = (level) ->
	svga.push @
	s = ""
	s += "<div id='bag"+@id+"' class='pyramid idea-bag"+level+"'>"
	s += "<div id='txt"+@id+"' class='idea-txt"+level+"'>"
	s += @txt if @txt?
	s += "</div>"	

	# Стикеры
	if @sticker? and @sticker.length > 0
		for sti in @sticker.data
			s += "<div id='sti"+sti.id+"' class='idea-sti'>"
			s += sti.txt
			s += "</div>"

	if (level is 0) or (level > 0 and not @frame?)
		for ia in @data
			s += ia.html(level+1)
	s += "</div>"
	s
*/


navi[PIECHART] = function(eo) {
  var sia;
  if ($txt.attr("contentEditable") === "true") {
    return navi[IDEA](eo);
  }
  switch (eo.which) {
    case 40:
      if (sidea === fidea) {
        if (sidea[0] != null) {
          return sidea[0].select();
        }
      } else {
        if ((!sidea.frame) && (sidea[0] != null)) {
          return sidea[0].select();
        } else {
          sia = sidea;
          while (sia !== fidea && !(sia.pa[sia.ix + 1] != null)) {
            sia = sia.pa;
          }
          if (sia !== fidea) {
            return sia.pa[sia.ix + 1].select();
          }
        }
      }
      break;
    default:
      return navi[IDEA](eo);
  }
};

/*
# Уровень пирамиды
navi[LAYER] = (eo) ->
	if $txt.attr("contentEditable") is "true" then return navi[IDEA](eo)
	switch eo.which
		when 40 # Down
			if sidea.pa[sidea.ix+1]? then sidea.pa[sidea.ix+1].select()
		when 38 # Up
			if sidea.pa[sidea.ix-1]? then sidea.pa[sidea.ix-1].select()
			else sidea.pa.select()
		else navi[IDEA](eo)
*/

