// Generated by CoffeeScript 1.3.3

sample.market = function() {
  var beeline, ma, marketMenu, marketRecalculate, marketop, marketshare, megafon, mm, ms, mts, opfld1, opfld2, opflds, prochie, svyaz;
  window.market = adf("Рынок сотовой связи", {
    description: add("Структура рынка сотовой связи"),
    readonly: true,
    nochildren: true,
    guide: add("Рассмотрите и проанализируйте рынок сотовой связи России")
  });
  mts = add("МТС", {
    readonly: true,
    nochildren: true
  });
  beeline = add("Билайн", {
    readonly: true,
    nochildren: true
  });
  megafon = add("Мегафон", {
    description: add("Быстрорастущий оператор связи")
  });
  svyaz = add("Связьинвест", {
    readonly: true,
    nochildren: true
  });
  prochie = add("Прочие", {
    readonly: true,
    nochildren: true
  });
  opfld1 = add("Оператор", {
    keyfield: true,
    readonly: true,
    nochildren: true
  });
  opfld2 = add("Доля рынка", {
    readonly: true,
    nochildren: true
  });
  opflds = add([opfld1, opfld2]);
  marketop = add("Таблица операторов связи", {
    field: opflds,
    readonly: true,
    nochildren: true
  });
  marketop.push(add([
    mts, add("34.3", {
      nochildren: true,
      format: PERCENT,
      refresh: true
    })
  ]));
  marketop.push(add([
    beeline, add("25.2", {
      nochildren: true,
      sticker: add([add("Отметим этого оператора")]),
      format: PERCENT,
      refresh: true
    })
  ]));
  marketop.push(add([
    megafon, add("23.2", {
      nochildren: true,
      format: PERCENT,
      refresh: true
    })
  ]));
  marketop.push(add([
    svyaz, add("7.2", {
      nochildren: true,
      format: PERCENT,
      refresh: true
    })
  ]));
  marketop.push(add([
    prochie, add("10.1", {
      nochildren: true,
      format: PERCENT,
      refresh: true
    })
  ]));
  marketop.kindTable();
  marketshare = add("Доли операторов рынка", {
    kind: PIECHART,
    source: marketop,
    nochildren: true
  });
  mm = add("Таблица");
  mm.push(add([(ma = add("")), (ms = add(""))]));
  mm.kindMatrix();
  ms.push(marketshare);
  ma.push(marketop);
  window.market.push(mm);
  window.market.next = add("Пересчитать диаграмму", {
    run: function() {
      return fidea.fhtml();
    }
  });
  marketRecalculate = add("Перерисовать диаграмму", {
    kind: MENUITEM,
    goto: window.market
  });
  marketMenu = add("Рынок сотовой связи", [marketRecalculate], {
    kind: MENU
  });
  return window.market.menu = marketMenu;
};
