// Generated by CoffeeScript 1.3.3

sample.lisp = function() {
  var ia, lans, ls, qls, rst, wansw, wzap, _i, _len;
  ls = "(define idea (quote (";
  for (_i = 0, _len = idea.length; _i < _len; _i++) {
    ia = idea[_i];
    ls += " #" + (-ia.id);
  }
  ls += ")))";
  lans = p(lispvalue(s(ls)));
  qls = "(car idea)";
  lans = p(lispvalue(s(qls)));
  rst = lans.match(/^(.*)([#][0-9]*)(.*)$/);
  while (rst) {
    lans = rst[1] + "'" + idea[rst[2].substr(1)].txt + "'" + rst[3];
    rst = lans.match(/^(.*)([#][0-9]*)(.*)$/);
  }
  window.wlisp = adf("Программа на языке Лисп");
  wzap = add("Запрос");
  wzap.push(add(qls));
  wansw = add("Ответ");
  wansw.push(add(lans));
  return window.wlisp.push(wzap, wansw);
};
