// Generated by CoffeeScript 1.3.3

sample.anketa = function() {
  var anb, anq1, anq2;
  window.ank = adf("Анкета лидера", {
    description: add("Многие управленческие методики предусматривают			анкетирование или ответы на тесты.")
  });
  anq1 = add("Я веду людей за собой", {
    format: YESNO
  });
  anq2 = add("Люди идут за мной", {
    format: YESNO
  });
  anb = add("Показать ответ", {
    kind: BUTTON,
    run: function() {
      if (window.anan == null) {
        window.anan = add("Вы - лидер!");
        window.ank.push(window.anan);
      }
      return window.ank.fhtml(window.anan);
    }
  });
  window.ank.push(anq1, anq2, anb);
  library.push(window.ank);
  return window.ank;
};
