// Generated by CoffeeScript 1.3.3

sample.quotes = function() {
  window.quotes = adf("Случайные цитаты", {
    description: add("Хорошая случайная цитата может подтолкнуть к хорошей идее.")
  });
  window.quobut = add("Нажмите, чтобы прочитать случайную цитату", {
    kind: BUTTON,
    run: function() {
      var qo;
      qo = [];
      qo[0] = "Хорошо-то хорошо, да ничего хорошего";
      qo[1] = "Хотели как лучше, получили как всегда";
      qo[2] = "Хорошо смеется последний";
      window.quota.txt = qo[Math.floor(Math.random() * 10) % 3];
      return quotes.fhtml(window.quobut);
    }
  });
  window.quota = add("Сосредоточьтесь!");
  return window.quotes.push(quota, quobut);
};
