// Generated by CoffeeScript 1.3.3

keyp[STICKER] = {};

childkind[STICKER] = function() {
  return IDEA;
};

Idea.prototype.kindSticker = function() {
  return this.kind = STICKER;
};

clas[STICKER] = "sticker";

draw[STICKER] = function(level, drawshow) {
  var angle, ix, s, sd, sh;
  s = "";
  sh = this.scheme != null ? this.scheme : WHITE;
  if (isNaN(this.sd)) {
    sd = 0;
  } else {
    sd = this.sd;
  }
  ix = this.ix;
  angle = (-this.id * 3 + sd * 5 + ix * 13) % 20 - 10;
  this.bagstyle = "background-color:" + schemes[sh][5] + ";color:Black;";
  this.bagstyle += "-webkit-transform:rotate(" + angle + "deg)";
  s += draw[DEFAULT].call(this, level, drawshow);
  return s;
};
