// Generated by CoffeeScript 1.3.3

keyp[TAG] = {};

childkind[TAG] = function() {
  return null;
};

Idea.prototype.kindTag = function() {
  return this.kind = TAG;
};

draw[TAG] = function(level) {
  var s;
  s = this.simpleIdeaTxt(level);
  return s;
};

clas[TAG] = "tag";
