// Generated by CoffeeScript 1.3.3
var setMenuText, text2Background, text2TableClass, textBottom, textCenter, textChildrenCenter, textChildrenJustify, textChildrenLeft, textChildrenRight, textClearAlign, textJustify, textLeft, textMiddle, textRight, textSchemeBlack, textSchemeBlue, textSchemeGreen, textSchemeLightBlue, textSchemeRed, textSchemeWhite, textSchemeYellow, textTop;

setMenuText = function() {
  $(".text_left").click(textLeft);
  $(".text_center").click(textCenter);
  $(".text_right").click(textRight);
  $(".text_justify").click(textJustify);
  $(".text_bottom").click(textBottom);
  $(".text_middle").click(textMiddle);
  $(".text_Top").click(textTop);
  $(".text_schemewhite").click(textSchemeWhite);
  $(".text_schemeblue").click(textSchemeBlue);
  $(".text_schemelightblue").click(textSchemeLightBlue);
  $(".text_schemegreen").click(textSchemeGreen);
  $(".text_schemeyellow").click(textSchemeYellow);
  $(".text_schemered").click(textSchemeRed);
  $(".text_schemeblack").click(textSchemeBlack);
  $(".text_childrenleft").click(textChildrenLeft);
  $(".text_childrencenter").click(textChildrenCenter);
  $(".text_childrenright").click(textChildrenRight);
  $(".text_childrenjustify").click(textChildrenJustify);
  $(".text_clearalign").click(textClearAlign);
  $(".text2_background").click(text2Background);
  return $(".text2_tableclass").click(text2TableClass);
};

text2Background = function() {
  if (fidea.background != null) {
    fidea.background = (fidea.background + 1) % bkgStyle.length;
  } else {
    fidea.background = 1;
  }
  return redraw();
};

text2TableClass = function() {
  if (sidea.tableclass != null) {
    sidea.tableclass = (sidea.tableclass + 1) % tblClass.length;
  } else {
    sidea.tableclass = 1;
  }
  return redraw();
};

textClearAlign = function() {
  delete sidea.align;
  delete sidea.childrenalign;
  delete sidea.valign;
  return redraw();
};

textLeft = function() {
  if (((sidea.align != null) && sidea.align !== LEFT) || (!(sidea.align != null))) {
    sidea.align = LEFT;
  } else {
    delete sidea.align;
  }
  return redraw();
};

textCenter = function() {
  if (((sidea.align != null) && sidea.align !== CENTER) || (!(sidea.align != null))) {
    sidea.align = CENTER;
  } else {
    delete sidea.align;
  }
  return redraw();
};

textRight = function() {
  if ((!(sidea.align != null)) || ((sidea.align != null) && (sidea.align !== RIGHT))) {
    sidea.align = RIGHT;
  } else {
    delete sidea.align;
  }
  return redraw();
};

textJustify = function() {
  if (((sidea.align != null) && sidea.align !== JUSTIFY) || (!(sidea.align != null))) {
    sidea.align = JUSTIFY;
  } else {
    delete sidea.align;
  }
  return redraw();
};

textTop = function() {
  if (((sidea.valign != null) && sidea.valign !== TOP) || (!(sidea.valign != null))) {
    sidea.valign = TOP;
  } else {
    delete sidea.valign;
  }
  return redraw();
};

textMiddle = function() {
  if (((sidea.valign != null) && sidea.valign !== MIDDLE) || (!(sidea.valign != null))) {
    sidea.valign = MIDDLE;
  } else {
    delete sidea.valign;
  }
  return redraw();
};

textBottom = function() {
  if (((sidea.valign != null) && sidea.valign !== BOTTOM) || (!(sidea.valign != null))) {
    sidea.valign = BOTTOM;
  } else {
    delete sidea.valign;
  }
  return redraw();
};

textSchemeWhite = function() {
  if ((sidea.scheme != null) && sidea.scheme === WHITE) {
    delete sidea.scheme;
  } else {
    sidea.scheme = WHITE;
  }
  return redraw();
};

textSchemeBlue = function() {
  if ((sidea.scheme != null) && sidea.scheme === BLUE) {
    delete sidea.scheme;
  } else {
    sidea.scheme = BLUE;
  }
  return redraw();
};

textSchemeLightBlue = function() {
  if ((sidea.scheme != null) && sidea.scheme === LIGHTBLUE) {
    delete sidea.scheme;
  } else {
    sidea.scheme = LIGHTBLUE;
  }
  return redraw();
};

textSchemeGreen = function() {
  if ((sidea.scheme != null) && sidea.scheme === GREEN) {
    delete sidea.scheme;
  } else {
    sidea.scheme = GREEN;
  }
  return redraw();
};

textSchemeYellow = function() {
  if ((sidea.scheme != null) && sidea.scheme === YELLOW) {
    delete sidea.scheme;
  } else {
    sidea.scheme = YELLOW;
  }
  return redraw();
};

textSchemeRed = function() {
  if ((sidea.scheme != null) && sidea.scheme === RED) {
    delete sidea.scheme;
  } else {
    sidea.scheme = RED;
  }
  return redraw();
};

textSchemeBlack = function() {
  if ((sidea.scheme != null) && sidea.scheme === BLACK) {
    delete sidea.scheme;
  } else {
    sidea.scheme = BLACK;
  }
  return redraw();
};

textChildrenLeft = function() {
  if ((sidea.childrenchildrenalign && sidea.childrenalign !== LEFT) || (!(sidea.childrenalign != null))) {
    sidea.childrenalign = LEFT;
  } else {
    delete sidea.childrenalign;
  }
  return redraw();
};

textChildrenCenter = function() {
  if (((sidea.childrenalign != null) && sidea.childrenalign !== CENTER) || (!(sidea.childrenalign != null))) {
    sidea.childrenalign = CENTER;
  } else {
    delete sidea.childrenalign;
  }
  return redraw();
};

textChildrenRight = function() {
  if ((!(sidea.childrenalign != null)) || ((sidea.childrenalign != null) && (sidea.childrenalign !== RIGHT))) {
    sidea.childrenalign = RIGHT;
  } else {
    delete sidea.childrenalign;
  }
  return redraw();
};

textChildrenJustify = function() {
  if (((sidea.childrenalign != null) && sidea.childrenalign !== JUSTIFY) || (!(sidea.childrenalign != null))) {
    sidea.childrenalign = JUSTIFY;
  } else {
    delete sidea.childrenalign;
  }
  return redraw();
};
