// Generated by CoffeeScript 1.3.3

keyp[TICK] = {};

childkind[TICK] = function() {
  return null;
};

notxt[TICK] = true;

Idea.prototype.kindTick = function() {
  return this.kind = TICK;
};

drtxt[TICK] = function(level) {
  var s;
  s = "";
  if (this.val == null) {
    s += "<span id='tik" + this.id + "' class='tick-undefined'></span>";
  } else if (this.val === true) {
    s += "<span id='tik" + this.id + "' class='tick-yes'></span>";
  } else if (this.val === false) {
    s += "<span id='tik" + this.id + "' class='tick-no'></span>";
  }
  return s;
};

clas[TICK] = "tick";

keyp[TICK][KEY_ENTER] = function() {
  var $tik;
  if (this.kind === TICK) {
    if (sidea.val == null) {
      sidea.val = true;
    } else if (sidea.val === true) {
      sidea.val = false;
    } else {
      sidea.val = null;
    }
    $tik = $('#tik' + sidea.id);
    $tik.removeClass("tick-yes");
    $tik.removeClass("tick-no");
    $tik.removeClass("tick-undefined");
    if (this.val == null) {
      return $tik.addClass("tick-undefined");
    } else if (this.val === true) {
      return $tik.addClass("tick-yes");
    } else if (this.val === false) {
      return $tik.addClass("tick-no");
    }
  }
};

keyp[TICK][KEY_F2] = keyp[TICK][KEY_ENTER];
