// Generated by CoffeeScript 1.3.3
﻿;

var $$bell, $$tick, changeTime, clickTimer, setTimer, timer;

timer = {};

$$tick = null;

$$bell = null;

setTimer = function() {
  timer.state = false;
  $("#timer").click(clickTimer);
  $$tick = document.getElementById("tick-audio");
  return $$bell = document.getElementById("bell-audio");
};

changeTime = function() {
  $("#time").html("&nbsp;" + Math.floor(timer.seconds / 60) + ":" + ("0" + timer.seconds % 60).substr(-2));
  timer.seconds -= 1;
  if (timer.seconds <= 0) {
    clearInterval(timer.interval);
    timer.state = false;
    alert("Время закончилось!");
    $("#time").html("Таймер");
    $$bell.load();
    $$bell.play();
  }
  if ((timer.seconds % 60) === 0 || (timer.seconds < 10) || ((timer.seconds < 60) && ((timer.seconds % 10) === 0))) {
    $$tick.load();
    return $$tick.play();
  }
};

clickTimer = function() {
  if (timer.state === false) {
    timer.minutes = prompt("На сколько минут поставить таймер", "15");
    timer.seconds = timer.minutes * 60;
    timer.interval = setInterval(changeTime, 1000);
    return timer.state = true;
  } else {
    clearInterval(timer.interval);
    timer.state = false;
    return $("#time").html("Таймер");
  }
};
