// Generated by CoffeeScript 1.3.3
var setMenuView, showFullScreen, viewBallon, viewComment, viewDescription, viewFullScreen, viewGuide, viewSticker, viewTimer, viewTodo;

setMenuView = function() {
  $(".view_fullscreen").click(viewFullScreen);
  $(".view_description").click(viewDescription);
  $(".view_guide").click(viewGuide);
  $(".view_todo").click(viewTodo);
  $(".view_comment").click(viewComment);
  $(".view_sticker").click(viewSticker);
  $(".view_ballon").click(viewBallon);
  return $(".view_timer").click(viewTimer);
};

showFullScreen = function() {
  $('#navbar').hide();
  $('#toolbar').hide();
  return $('body').css("padding-top", "0px");
};

viewFullScreen = function() {
  $('#navbar').toggle();
  if ($('#navbar').css("display") === "none") {
    $('body').css("padding-top", "0px");
    $('#toolbar').hide();
  } else {
    $('body').css("padding-top", "40px");
    $('#toolbar').show();
  }
  return redraw();
};

viewDescription = function() {
  return alert("Эта функция будет реализована в следующих версиях программы");
};

viewGuide = function() {
  return alert("Эта функция будет реализована в следующих версиях программы");
};

viewTodo = function() {
  return alert("Эта функция будет реализована в следующих версиях программы");
};

viewComment = function() {
  return alert("Эта функция будет реализована в следующих версиях программы");
};

viewSticker = function() {
  return alert("Эта функция будет реализована в следующих версиях программы");
};

viewBallon = function() {
  return alert("Эта функция будет реализована в следующих версиях программы");
};

viewTimer = function() {
  $('#timer').toggle();
  if ($('#timer').css("display") === "none") {
    return $('#icon-timer').hide();
  } else {
    return $('#icon-timer').show();
  }
};
